---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    organization: Default Organization
    lifecycle_environment: "{{ content_view }}_{{ env }}"
    content_view: undef

  tasks:
  - name: Publish Content View
    redhat.satellite.content_view_version:
      content_view: "{{ content_view }}"
      organization: "{{ organization }}"
      lifecycle_environments: "{{ lifecycle_environment }}"
